import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import type { Session } from "next-auth";
import Providers from "./Providers";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Simply Good Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
        <Providers>
            <Toaster position="top-right" />

            {children}
          </Providers>
        </>
      </body>
    </html>
  );
}
